config/routes.rb
Rails3Extjs4::Application.routes.draw do
  root :to => "index#index"

  devise_for :users

  resources :search_suggestions

  resources :gundams do
    resources :gundam_photos, :only => [:new, :create, :show]
  end

  resources :gundam_photos, :only => [:index, :avatar] do 
    get 'avatar', :on => :member
    post 'crop', :on => :member
  end

  get '/search' => "search#index"

  resources :versions do
    member do
      put "merge"
    end
  end

  namespace "admin" do
    root :to => "index#index"

    resources :drivers do 
      collection do
        get 'index_data'
        get 'edit_data'
      end
    end

    resources :gundams do 
      collection do
        get 'index_data'
        get 'edit_data'
        get 'send_info'
      end
    end

    resources :gundam_photos do 
      collection do
        get 'index_data'
        get 'edit_data'
        post 'set_verified'
      end
    end

    resources :periods do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :usages do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :users do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :dimensions do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    match "/processes" => ProcessesApp
  end

end

app/views/index/index.html.erb
<% content_for :header do%>
  <title>rails3_extjs4</title>
<% end %>
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <center><img src="/images/index_1.jpg" alt=""></center>
      <div class="container">
      </div>
    </div>
    <div class="item">
      <center><img src="/images/index_2.jpg" alt=""></center>
      <div class="container">
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>

<% if user_signed_in? %>
  welcome to my web!
  <%= link_to 'Edit profile', edit_user_registration_path, class:"btn btn-primary" %> |
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn btn-primary" %> |
  <%= link_to "Admin", admin_root_path, class:"btn btn-primary" %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-primary" %> |
  <%= link_to 'Login', new_user_session_path, class:"btn btn-primary" %>
<% end %>