config/routes.rb
Rails3Extjs4::Application.routes.draw do
  root :to => "index#index"

  devise_for :users

  resources :search_suggestions

  resources :gundams do
    resources :gundam_photos, :only => [:new, :create, :show]
  end

  resources :gundam_photos, :only => [:index, :avatar] do 
    get 'avatar', :on => :member
    post 'crop', :on => :member
  end

  get '/search' => "search#index"

  resources :versions do
    member do
      put "merge"
    end
  end

  namespace "admin" do
    root :to => "index#index"

    resources :drivers do 
      collection do
        get 'index_data'
        get 'edit_data'
      end
    end

    resources :gundams do 
      collection do
        get 'index_data'
        get 'edit_data'
        get 'send_info'
      end
    end

    resources :gundam_photos do 
      collection do
        get 'index_data'
        get 'edit_data'
        post 'set_verified'
      end
    end

    resources :periods do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :usages do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :users do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :dimensions do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    match "/processes" => ProcessesApp
  end

end

app/controllers/versions_controller.rb
# coding: utf-8
class VersionsController < ApplicationController
  def index
  end

  def show
    if request.xhr?
      @version = GundamVersion.find(params[:id])
    else
      @gundam = Gundam.find(params[:id])
      @version = @gundam.versions.first
    end
  end

  def new

  end

  def create

  end

  def merge
    
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
  include HTMLDiff
  def showdiff(gundam,version,*attr_names)
    gundam_attr = gundam
    version_attr = version
    attr_names.each do |attr_name|
      gundam_attr = gundam_attr.try(attr_name)
      version_attr = version_attr.try(attr_name)
    end
    version_attr.nil? ? gundam_attr : diff(gundam_attr||'',version_attr)
  end
end

app/views/versions/_show_diff.html.erb
<div>
    <table class="table table-bordered table-hover">
      <tr width="250px">
        <td colspan="2" rowspan="12" width='50%'><div><%= image_tag(@gundam.avatar_url(:big)) %></div></td>
        <td class="attribute">版本</td>
        <td class='value'><%= version.version %></td>
      </tr>
      <tr>
        <td class="attribute">年代</td>
        <td class='value'><%= "#{raw showdiff(gundam,version,"period","year")} #{raw showdiff(gundam,version,"period","name")}" %></td>
      </tr>
      <tr>
        <td class="attribute">型号</td>
        <td class='value'><%= raw showdiff(gundam,version,"model") %></td>
      </tr>
      <tr>
        <td class="attribute">英文</td>
        <td class='value'><%= raw showdiff(gundam,version,"name") %></td>
      </tr>
      <tr>
        <td class="attribute">日文名</td>
        <td class='value'><%= raw showdiff(gundam,version,"name_jp") %></td>
      </tr>
      <tr>
        <td class="attribute">中文名</td>
        <td class='value'><%= raw showdiff(gundam,version,"name_chs") %></td>
      </tr>
      <tr>
        <td class="attribute">机体类型</td>
        <td class='value'><%= raw showdiff(gundam,version,"usage","name") %></td>
      </tr>
      <tr>
        <td class="attribute">制造商</td>
        <td class='value'><%= raw showdiff(gundam,version,"manufactory","name") %></td>
      </tr>
      <tr>
        <td class="attribute">所属</td>
        <td class='value'><%= gundam.forces.first.try(:name) %></td>
      </tr>
      <tr>
        <td class="attribute">重量</td>
        <td class='value'><%= raw showdiff(gundam,version,"weight") %></td>
      </tr>
      <tr>
        <td class="attribute">尺寸</td>
        <td class='value'><%= raw showdiff(gundam,version,"measurement") %></td>
      </tr>
      <tr>
        <td class="attribute">出现作品</td>
        <td class='value'><%= raw showdiff(gundam,version,"story","name") %></td>
      </tr>
       <tr>
        <td colspan="4"><%= raw showdiff(gundam,version,"summary") %></td>
      </tr>
      <tr>
        <td class="attribute">内部环境</td>
        <td class='value'><%= raw showdiff(gundam,version,"internal_environment") %></td>
        <td class="attribute">装甲材料及结构</td>
        <td class='value'><%= raw showdiff(gundam,version,"armor") %></td>
      </tr>
      <tr>
        <td class="attribute">发电机出力</td>
        <td class='value'><%= raw showdiff(gundam,version,"output") %></td>
        <td class="attribute">推进力</td>
        <td class='value'><%= raw showdiff(gundam,version,"propulsion") %></td>
      </tr>
      <tr>
        <td class="attribute">加速度</td>
        <td class='value'><%= raw showdiff(gundam,version,"acceleration") %></td>
        <td class="attribute">装备及设计特征</td>
        <td class='value'><%= raw showdiff(gundam,version,"special_equipped") %></td>
      </tr>
      <tr>
        <td class="attribute">固定武装</td>
        <td class='value'><%= raw showdiff(gundam,version,"default_weapon") %></td>
        <td class="attribute">选用武装</td>
        <td class='value'><%= raw showdiff(gundam,version,"selected_weapon") %></td>
      </tr>
      <tr>
        <td class="attribute">选用手部武器</td>
        <td class='value'><%= raw showdiff(gundam,version,"hand_weapon") %></td>
        <td class="attribute">远程武器</td>
        <td class='value'><%= raw showdiff(gundam,version,"ranged_weapon") %></td>
      </tr>
    </table>
    <%= button_to '合并', merge_version_path(version), class: "btn btn-primary" %>
</div>

app/views/versions/index.html.erb
<h1>Versions#index</h1>
<p>Find me in app/views/versions/index.html.erb</p>

app/views/versions/merge.html.erb
<h1>Versions#merge</h1>
<p>Find me in app/views/versions/merge.html.erb</p>

app/views/versions/show.html.erb
<h1><%= @gundam.name %></h1>
<table class='table table-striped version_list'>
  <% @gundam.unmerge_versions.each_with_index do |version,index| %>
    <tr data-version='<%= version.id %>'>
      <td>#<%= index+1 %></td>
      <td><%= version.created_at %></td>
      <td><%= version.version %></td>
    </tr>
  <% end %>
</table>
<!--<%= @version.id %>-->
<div id='diff_form'>
  <%= render :partial => 'show_diff', :locals => { gundam: @gundam, version: @version } %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.version_list tr').click(function(){
      $.ajax({
        type: 'get',
        url: '/versions/'+$(this).attr('data-version'),
        dataType: 'script'
      })
    })
  })
</script>

app/views/versions/show.js.erb
$('#diff_form').html("<%= j render(:partial => 'show_diff', :locals => { gundam: @version.gundam, version: @version }) %>");