config/routes.rb
Rails3Extjs4::Application.routes.draw do
  root :to => "index#index"

  devise_for :users

  resources :search_suggestions

  resources :gundams do
    resources :gundam_photos, :only => [:new, :create, :show]
  end

  resources :gundam_photos, :only => [:index, :avatar] do 
    get 'avatar', :on => :member
    post 'crop', :on => :member
  end

  get '/search' => "search#index"

  resources :versions do
    member do
      put "merge"
    end
  end

  namespace "admin" do
    root :to => "index#index"

    resources :drivers do 
      collection do
        get 'index_data'
        get 'edit_data'
      end
    end

    resources :gundams do 
      collection do
        get 'index_data'
        get 'edit_data'
        get 'send_info'
      end
    end

    resources :gundam_photos do 
      collection do
        get 'index_data'
        get 'edit_data'
        post 'set_verified'
      end
    end

    resources :periods do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :usages do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :users do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :dimensions do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    match "/processes" => ProcessesApp
  end

end

app/models/gundam.rb
# coding: utf-8
class Gundam < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include Tire::Model::Search
  include Tire::Model::Callbacks
  include MongoSync
  
  # security (i.e. attr_accessible) ...........................................
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessible :name, :name_chs, :name_jp, :model, :period_id, :period, :usage_id, :usage, :avatar, :remote_avatar_url, :crop_x, :crop_y, :crop_w, :crop_h, :specifications, :internal_environment, :measurement, :weight, :armor, :output, :propulsion, :acceleration, :special_equipped, :default_weapon, :selected_weapon, :hand_weapon, :ranged_weapon, :summary
  
  # relationships .............................................................
  has_many :driver_gundams
  has_many :force_gundams
  has_many :forces, :through => :force_gundams
  has_many :gundam_photos
  has_many :versions, class_name: "GundamVersion"
  has_many :raw_gundams
  belongs_to :period
  belongs_to :usage
  belongs_to :manufactory
  belongs_to :story
  
  # validations ...............................................................
  validates :model, :presence => true, :uniqueness => {:message => "should have only one model per period", :on => :create}

  # callbacks .................................................................
  before_save :reprocess_avatar, :if => :cropping?
  
  # 解决mongo数据无法被同步更新的问题
  after_save do 
    mongo.update_attribute(:avatar, self.attributes["avatar"])
  end

  # scopes ....................................................................
  scope :from_period, lambda{ |period_id| where(period_id: period_id) if period_id.present?}
  scope :from_dimension, lambda{ |period_id, dimension_id|
    if period_id.blank? and dimension_id.present?
      where(period_id: Period.where(dimension_id: dimension_id).map(&:id))
    end
  }

  # additional config .........................................................
  mount_uploader :avatar, GundamAvatarUploader

  # attr_accessor :story_name, :usage_name, :manufactory_name, :force_name, :period_name
  # def init_names
  #   %w{story usage manufactory force period}.each do |source|
  #     if send("#{source}_name").present?
  #       instance_variable_set("#{source}_class_id") = source.classify.constantize.where(name: send("#{source}_name")).first_or_create
  #       send("#{source}_id=(#{instance_variable_get("#{source}_class_id")})")
  #     end
  #   end
  # end

  # class methods .............................................................
  def self.search_by_keywords(params = {})

    periods = PeriodMongo.where(dimension_id: params[:dimension_id].to_i).map(&:id) if params[:dimension_id].present?
    periods = params[:period_id] if params[:period_id].present?

    tire.search(page: params[:page] || 1, per_page: params[:per_page] || 20) do
      query do
        boolean do
          should { match :model, params[:query], boost: 10 }
          should { match :name, params[:query], boost: 10 }
          should { match :name_chs, params[:query], boost: 10 }
          should { match :period_name, params[:query] }
          should { match :period_year, params[:query] }
          should { match :dimension_name, params[:query] }
        end
      end if params[:query].present?
      filter :terms, :period_id => periods.to_a if periods.present?
      sort do
        by :dimension_id, "desc"
        by :period_year_sort, "asc"
      end if params[:query].blank?
    end

  end

  # public instance methods ...................................................
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end 
  
  def reprocess_avatar
    self.avatar.recreate_versions!
  end

  def to_indexed_json
    to_json(:methods => [:period_year, :period_year_sort, :period_name, :dimension_id, :dimension_name])
  end

  def period_year
    period.try(:year)
  end

  def period_year_sort
    period.try(:year).to_i
  end

  def period_name
    period.try(:name)
  end

  def dimension_id
    period.try(:dimension).try(:id)
  end

  def dimension_name
    period.try(:dimension).try(:name)
  end

  # protected instance methods ................................................
  # private instance methods ..................................................

end

app/controllers/admin/gundams_controller.rb
# coding: utf-8
class Admin::GundamsController < Admin::ApplicationController

  # POST /gundams
  def create
    params_hash = {:name=>params[:name],:model=>params[:model],:name_chs=>params[:name_chs],
      :period_id=>params[:period],:usage_id=>params[:usage]}
    @obj = Gundam.new(params_hash)
    if @obj.save
      render :json=>{:success=>true}
    else
      render :json=>{:success=>false,:info=>@obj.errors.full_messages}
    end
  end

  # DELETE /gundams/1
  def destroy
    @obj = Gundam.find(params[:id])
    @obj.destroy
    render :json=>{:success=>true}
  end

  def edit_data
    render :json=>Gundam.find(params[:id]), :layout=>false
  end

  # PUT /gundams/1
  def update
    gundam = Gundam.find(params[:id])
    if gundam.update_attributes(params.except(:id, :controller, :action))
      render :json=>{:success=>true}
    else
      render :json=>{:success=>false,:info=>@obj.errors.full_messages}
    end
  end

  # GET /index_data
  def index_data
    gundams = Gundam.includes(:usage, :raw_gundams, [:period=>:dimension]).limit(params[:limit]).offset(params[:start])  
    render :text=>"{'totalProperty':#{Gundam.count},'root':#{gundams.to_json(:include=>[:usage, :raw_gundams, :period => {:include=>:dimension}])}}", :layout=>false
  end

  # GET /send_info
  def send_info
    emails = emails || ["wxl_test@126.com"]
    emails.each do |email|
      Resque.enqueue(InfoMailer, email, params[:gundam_id])
    end
    render :json=>{:success=>true}
  end

end

app/controllers/gundams_controller.rb
# coding: utf-8
class GundamsController < ApplicationController

  # GET /gundams
  def index
    ## use mysql
    # @gundams = Gundam.from_dimension(params[:period_id], params[:dimension_id]).from_period(params[:period_id]).includes(:period).order("periods.year").paginate(:page=>params[:page] || 1, :per_page => 20)

    ## use mongo
    periods_array = PeriodMongo.asc(:year).map(&:id)
    if params[:period_id].present? or params[:dimension_id].present?
      @gundams = Kaminari.paginate_array(GundamMongo.from_dimension(params[:period_id], params[:dimension_id]).from_period(params[:period_id]).includes(:period).sort_by{|o| periods_array.index(o.period_id)}).page(params[:page]).per(20)
    else
      @gundams = Kaminari.paginate_array(GundamMongo.where(:period_id.in => periods_array).includes(:period).sort_by{|o| periods_array.index(o.period_id)}).page(params[:page]).per(20)
    end
    @search = Search.new(params)
    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /gundams/1/edit
  def edit
    @gundam = Gundam.find(params[:id])
    @gundam_version = GundamVersion.new(gundam_id: @gundam.id)
  end

  # PUT /gundams/1
  # PUT /gundams/1.json
  def update
    @gundam = Gundam.find(params[:id])
    @version = @gundam.versions.new(params[:gundam])
    if @version.save
      redirect_to @gundam, notice: '您的更改已经保存，请等待管理员审批。'
    else
      @gundam.assign_attributes(params[:gundam])
      render action: :edit
    end
  end

  # GET /gundams/1
  # GET /gundams/1.json
  def show
    @gundam = GundamMongo.find(params[:id])
    @gundam_photos = GundamPhotoMongo.verified.where(gundam_id: params[:id]).desc("id")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gundam }
    end
  end

end

app/views/gundams/_list.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>大头贴</th>
      <th>时期</th>
      <th>型号</th>
      <th>英文名</th>
      <th>中文名</th>
    </tr>
  </thead>
  <tbody>
    <% gundams.each do |gundam| %>
      <tr>
        <td><%= link_to image_tag(gundam.avatar_url(:thumb)), gundam %></td>
        <td><%= year_title gundam.period %></td>
        <td><%= link_to gundam.model, gundam %></td>
        <td><%= link_to gundam.name, gundam %></td>
        <td><%= link_to gundam.name_chs, gundam %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate gundams, :renderer => BootstrapPagination::Rails %>

app/views/gundams/_show_diff.html.erb
<div>
    <table class="table table-bordered table-hover">
      <tr width="250px">
        <td colspan="2" rowspan="12" width='50%'><div><%= image_tag(@gundam.avatar_url(:big)) %></div></td>
        <td class="attribute">版本</td>
        <td class='value'><%= params[:id] %></td>
      </tr>
      <tr>
        <td class="attribute">年代</td>
        <td class='value'><%= "#{raw showdiff(gundam,version,"period","year")} #{raw showdiff(gundam,version,"period","name")}" %></td>
      </tr>
      <tr>
        <td class="attribute">型号</td>
        <td class='value'><%= raw showdiff(gundam,version,"model") %></td>
      </tr>
      <tr>
        <td class="attribute">英文</td>
        <td class='value'><%= raw showdiff(gundam,version,"name") %></td>
      </tr>
      <tr>
        <td class="attribute">日文名</td>
        <td class='value'><%= raw showdiff(gundam,version,"name_jp") %></td>
      </tr>
      <tr>
        <td class="attribute">中文名</td>
        <td class='value'><%= raw showdiff(gundam,version,"name_chs") %></td>
      </tr>
      <tr>
        <td class="attribute">机体类型</td>
        <td class='value'><%= raw showdiff(gundam,version,"usage","name") %></td>
      </tr>
      <tr>
        <td class="attribute">制造商</td>
        <td class='value'><%= raw showdiff(gundam,version,"manufactory","name") %></td>
      </tr>
      <tr>
        <td class="attribute">所属</td>
        <td class='value'><%= gundam.forces.first.try(:name) %></td>
      </tr>
      <tr>
        <td class="attribute">重量</td>
        <td class='value'><%= raw showdiff(gundam,version,"weight") %></td>
      </tr>
      <tr>
        <td class="attribute">尺寸</td>
        <td class='value'><%= raw showdiff(gundam,version,"measurement") %></td>
      </tr>
      <tr>
        <td class="attribute">出现作品</td>
        <td class='value'><%= raw showdiff(gundam,version,"story","name") %></td>
      </tr>
       <tr>
        <td colspan="4"><%= raw showdiff(gundam,version,"summary") %></td>
      </tr>
      <tr>
        <td class="attribute">内部环境</td>
        <td class='value'><%= raw showdiff(gundam,version,"internal_environment") %></td>
        <td class="attribute">装甲材料及结构</td>
        <td class='value'><%= raw showdiff(gundam,version,"armor") %></td>
      </tr>
      <tr>
        <td class="attribute">发电机出力</td>
        <td class='value'><%= raw showdiff(gundam,version,"output") %></td>
        <td class="attribute">推进力</td>
        <td class='value'><%= raw showdiff(gundam,version,"propulsion") %></td>
      </tr>
      <tr>
        <td class="attribute">加速度</td>
        <td class='value'><%= raw showdiff(gundam,version,"acceleration") %></td>
        <td class="attribute">装备及设计特征</td>
        <td class='value'><%= raw showdiff(gundam,version,"special_equipped") %></td>
      </tr>
      <tr>
        <td class="attribute">固定武装</td>
        <td class='value'><%= raw showdiff(gundam,version,"default_weapon") %></td>
        <td class="attribute">选用武装</td>
        <td class='value'><%= raw showdiff(gundam,version,"selected_weapon") %></td>
      </tr>
      <tr>
        <td class="attribute">选用手部武器</td>
        <td class='value'><%= raw showdiff(gundam,version,"hand_weapon") %></td>
        <td class="attribute">远程武器</td>
        <td class='value'><%= raw showdiff(gundam,version,"ranged_weapon") %></td>
      </tr>
    </table>
</div>

app/views/gundams/compare.js.erb
$('#diff_form').html("<%= j render(:partial => 'show_diff', :locals => { gundam: @gundam, version: @version }) %>");

app/views/gundams/edit.html.erb
<div class="row">
  <%= form_for @gundam do |f| %>
    <table class="table table-bordered table-hover">
      <tr>
        <td colspan="2" rowspan="11" width="250px"><div><%= image_tag(@gundam.avatar_url(:big)) %></div></td>
        <td>年代</td>
        <td><%= f.select :period_id, Period.all.collect{|e|[[e.year,e.name].join(' '),e.id]} %></td>
      </tr>
      <tr>
        <td>型号</td>
        <td><%= f.text_field :model %></td>
      </tr>
      <tr>
        <td>英文</td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td>日文名</td>
        <td><%= f.text_field :name_jp %></td>
      </tr>
      <tr>
        <td>中文名</td>
        <td><%= f.text_field :name_chs %></td>
      </tr>
      <tr>
        <td>机体类型</td>
        <td><%= f.select :usage_id, Usage.all.collect{|e|[e.name,e.id]} %></td>
      </tr>
      <tr>
        <td>制造商</td>
        <td><%= f.select :manufactory_id, Manufactory.all.collect{|e|[e.name,e.id]} %></td>
      </tr>
      <tr>
        <td>所属</td>
        <td><%= @gundam.forces.first.try(:name) %></td>
      </tr>
      <tr>
        <td>重量</td>
        <td><%= f.text_field :weight %></td>
      </tr>
      <tr>
        <td>尺寸</td>
        <td><%= f.text_field :measurement %></td>
      </tr>
      <tr>
        <td>出现作品</td>
        <td><%= f.select :story_id, Story.all.collect{|e|[e.name,e.id]} %></td>
      </tr>
       <tr>
        <td colspan="4"><%= @gundam.summary %></td>
      </tr>
      <tr>
        <td>内部环境</td>
        <td><%= f.text_field :internal_environment %></td>
        <td>装甲材料及结构</td>
        <td><%= f.text_field :armor %></td>
      </tr>
      <tr>
        <td>发电机出力</td>
        <td><%= f.text_field :output %></td>
        <td>推进力</td>
        <td><%= f.text_field :propulsion %></td>
      </tr>
      <tr>
        <td>加速度</td>
        <td><%= f.text_field :acceleration %></td>
        <td>装备及设计特征</td>
        <td><%= f.text_field :special_equipped %></td>
      </tr>
      <tr>
        <td>固定武装</td>
        <td><%= f.text_field :default_weapon %></td>
        <td>选用武装</td>
        <td><%= f.text_field :selected_weapon %></td>
      </tr>
      <tr>
        <td>选用手部武器</td>
        <td><%= f.text_field :hand_weapon %></td>
        <td>远程武器</td>
        <td><%= f.text_field :ranged_weapon %></td>
      </tr>
    </table>
    <%= f.submit '提交', class:"btn btn-primary" %>
  <% end %>
</div>

app/views/gundams/histroy.html.erb
<h1><%= @gundam.name %></h1>
<table class='table table-striped version_list'>
  <% @versions.each_with_index do |version,index| %>

    <tr data-version='<%= version.id %>'>
      <td>#<%= index+1 %></td>
      <td><%= version.id %></td>
    </tr>
  <% end %>
</table>
<div id='diff_form'>
  <%#= render :partial => 'show_diff', :locals => { gundam: @gundam, version: @version } %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.version_list tr').click(function(){
      $.ajax({
        type: 'get',
        url: 'compare?histroy='+$(this).attr('data-version'),
        dataType: 'script'
      })
    })
  })
</script>

app/views/gundams/index.html.erb
<% content_for :header do%>
  <%= javascript_include_tag  "gundams" %>
<%end%>
<%= collection_select :search, :dimension_id, DimensionMongo.asc(:name), :id, :name, prompt: true %>
<%= grouped_collection_select :search, :period_id, Dimension.order(:name).includes(:periods), :periods, :name, :id, :year, prompt: true %>
<div id="data-listArea">
  <%= render :partial => 'list', :locals => {:gundams => @gundams} %>
</div>

app/views/gundams/index.js.erb
$("#data-listArea").html("<%= j render :partial => 'list', :locals => {:gundams => @gundams} %>")

app/views/gundams/show.html.erb
<% content_for :header do%>
  <%= javascript_include_tag  "gundams" %>
<%end%>
<div class="row">
  <div class="span9">
    <table class="table table-bordered table-hover">
      <tr>
        <td colspan="2" rowspan="11"><%= link_to(image_tag(@gundam.avatar_url(:big)), @gundam.avatar_url, class: "cloud-zoom", rel: "adjustX:60,adjustY:0,smoothMove:1") %></td>
        <td>年代</td>
        <td><%= year_title @gundam.period %></td>
      </tr>
      <tr>
        <td>型号</td>
        <td><%= @gundam.model %></td>
      </tr>
      <tr>
        <td>英文</td>
        <td><%= @gundam.name %></td>
      </tr>
      <tr>
        <td>日文名</td>
        <td><%= @gundam.name_jp %></td>
      </tr>
      <tr>
        <td>中文名</td>
        <td><%= @gundam.name_chs %></td>
      </tr>
      <tr>
        <td>机体类型</td>
        <td><%= @gundam.usage.try(:name) %></td>
      </tr>
      <tr>
        <td>制造商</td>
        <td><%= @gundam.manufactory.try(:name) %></td>
      </tr>
      <tr>
        <td>所属</td>
        <td><%= @gundam.forces.first.try(:name) %></td>
      </tr>
      <tr>
        <td>重量</td>
        <td><%= @gundam.weight %></td>
      </tr>
      <tr>
        <td>尺寸</td>
        <td><%= @gundam.measurement %></td>
      </tr>
      <tr>
        <td>出现作品</td>
        <td><%= @gundam.story.try(:name) %></td>
      </tr>
       <tr>
        <td colspan="4"><%= @gundam.summary %></td>
      </tr>
      <tr>
        <td>内部环境</td>
        <td><%= @gundam.internal_environment %></td>
        <td>装甲材料及结构</td>
        <td><%= @gundam.armor %></td>
      </tr>
      <tr>
        <td>发电机出力</td>
        <td><%= @gundam.output %></td>
        <td>推进力</td>
        <td><%= @gundam.propulsion %></td>
      </tr>
      <tr>
        <td>加速度</td>
        <td><%= @gundam.acceleration %></td>
        <td>装备及设计特征</td>
        <td><%= @gundam.special_equipped %></td>
      </tr>
      <tr>
        <td>固定武装</td>
        <td><%= @gundam.default_weapon %></td>
        <td>选用武装</td>
        <td><%= @gundam.selected_weapon %></td>
      </tr>
      <tr>
        <td>选用手部武器</td>
        <td><%= @gundam.hand_weapon %></td>
        <td>远程武器</td>
        <td><%= @gundam.ranged_weapon %></td>
      </tr>
    </table>
    <%= link_to 'Upload photos', new_gundam_gundam_photo_path(@gundam), class:"btn btn-primary" %>
    <%= link_to 'Back', gundams_path, class:"btn" %>
    <%= link_to 'Edit', edit_gundam_path(@gundam), class:"btn" %>
    <div id="container">
      <% @gundam_photos.each do |gundam_photo| %>
        <div class="item">
          <a href="<%= gundam_photo.image_url(:big) %>" rel="lightbox" title="my caption"><%= image_tag gundam_photo.image_url(:list), class: "img-polaroid" %></a>
          <br />
          <a href="/gundam_photos/<%= gundam_photo.id %>/avatar" class="btn">设为头像</a>
        </div>
      <% end %>
    </div>
  </div>
  <div class="span3">
    <div class="span3" data-spy="affix" data-offset-top="0">
      <h2>About Us</h2>
      <p>We are Gundam fan ~~ and coder</p>
    </div>
  </div>
</div>
<!--
Button to trigger modal
<a href="#edit_form" role="button" class="btn" data-toggle="modal">纠错</a>
 
Modal
<div id="edit_form" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">编辑</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>
-->