config/routes.rb
Rails3Extjs4::Application.routes.draw do
  root :to => "index#index"

  devise_for :users

  resources :search_suggestions

  resources :gundams do
    resources :gundam_photos, :only => [:new, :create, :show]
  end

  resources :gundam_photos, :only => [:index, :avatar] do 
    get 'avatar', :on => :member
    post 'crop', :on => :member
  end

  get '/search' => "search#index"

  resources :versions do
    member do
      put "merge"
    end
  end

  namespace "admin" do
    root :to => "index#index"

    resources :drivers do 
      collection do
        get 'index_data'
        get 'edit_data'
      end
    end

    resources :gundams do 
      collection do
        get 'index_data'
        get 'edit_data'
        get 'send_info'
      end
    end

    resources :gundam_photos do 
      collection do
        get 'index_data'
        get 'edit_data'
        post 'set_verified'
      end
    end

    resources :periods do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :usages do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :users do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    resources :dimensions do 
      collection do
        get 'index_data'
        get 'all_data'
        get 'edit_data'
      end
    end

    match "/processes" => ProcessesApp
  end

end

app/models/usage.rb
# coding: utf-8
class Usage < ActiveRecord::Base
  include MongoSync

  has_many :gundams

  attr_accessible :name, :summary, :gundam_id

  validates :name, :presence => true, :uniqueness => true
end

app/controllers/admin/usages_controller.rb
# coding: utf-8
class Admin::UsagesController < Admin::ApplicationController
  # GET /types/new
  def new
  end

  # POST /types
  def create
    new = {:name=>params[:name]}
    @usage = Usage.new(new)
    if @usage.save
      render :json=>{:success=>true}
    else
      render :json=>{:success=>false,:info=>@usage.errors.full_messages}
    end
  end

  # DELETE /types/1
  def destroy
    @user = Usage.find(params[:id])
    @user.destroy
    render :json=>{:success=>true}
  end

  # GET /types/1/edit
  def edit
  end

  def edit_data
    render :json=>Usage.find(params[:id]), :layout=>false
  end

  # PUT /types/1
  def update
    @usage = Usage.find(params[:id])
    new = {:name=>params[:name]}
    if @usage.update_attributes(new)
      render :json=>{:success=>true}
    else
      render :json=>{:success=>false,:info=>@usage.errors.full_messages}
    end
  end

  # GET /types
  def index
  end

  def index_data
    types = Usage.limit(params[:limit]).offset(params[:start])
    render :text=>"{'totalProperty':#{Usage.count},'root':#{types.to_json()}}", :layout=>false
  end

  def all_data
    render :text=>"{'totalProperty':#{Usage.count},'root':#{Usage.select("id,name").to_json()}}", :layout=>false
  end
end

app/views/admin/usages/edit.html.erb
<% content_for :header do%>
  <script type="text/javascript">

    Ext.onReady(function(){
      Ext.define('WinThread', {
        extend: 'Ext.data.Model',
        fields: [
          {name: 'id'},
          {name: 'name'}
        ]
      });

      var winForm = new Ext.form.FormPanel({
        url:'admin/usages/<%=params[:id]%>',
        height: 132,
        width: 360,
        layout: 'absolute',
        border: false,
        frame:true,
        reader: new Ext.data.JsonReader({
          model: 'WinThread'
        }),
        items: [
          {
            xtype: 'label',
            x: 50,
            y: 30,
            height: 20,
            width: 60,
            text: '类型：'
          },
          {
            xtype: 'textfield',
            x: 110,
            y: 30,
            name: 'name',
            width: 210
          },
          {
            xtype: 'button',
            x: 130,
            y: 80,
            height: 30,
            width: 90,
            text: '保存',
            handler: function(){
              if (winForm.form.isValid()) {
                winForm.form.submit({
                  method: 'put',
                  waitMsg: '正在处理...',
                  success: function(result, response){
                    Ext.MessageBox.alert('提示', '成功！');
                    Ext.getCmp('win').close();
                  },
                  failure: function(result, response){
                    Ext.MessageBox.alert('错误提示', response.result.info);
                  }
                });
              }else {
                Ext.MessageBox.alert('错误提示', '请按要求填写必输选项.');
              }
            }
          }
        ]
      });
      winForm.form.load({
        url: 'admin/usages/edit_data?id='+<%=params[:id]%>,
        method: 'get',
        params: {
          authenticity_token: '<%= form_authenticity_token.to_s %>'
        },
        success: function(form, action){
        },
        failure: function(form, action){
          Ext.MessageBox.alert('提示信息', '信息加载失败');
        }
      });
      winForm.render('<%=params[:controller]%>_<%=params[:action]%>_div');
    });
  </script>
<%end%>

app/views/admin/usages/index.html.erb
<% content_for :header do%>
  <script type="text/javascript">

    Ext.onReady(function(){

      Ext.define('ForumThread', {
        extend: 'Ext.data.Model',
        fields: [
          {name: 'id'},
          {name: 'name'},
          {name: 'created_at'}
        ],
        idProperty: 'threadid'
      });

      common.usageslistDS = Ext.create('Ext.data.Store', {
        id: 'store',
        model: 'ForumThread',
        remoteGroup: true,
        pageSize: common.list_num,
        proxy: {
          type: 'ajax',
          url: '<%= index_data_admin_usages_path %>',
          reader: {
            root: 'root',
            totalProperty: 'totalProperty'
          },
          simpleSortMode: true,
          simpleGroupMode: true,
          groupParam: 'sort',
          groupDirectionParam: 'dir'
        },
        sorters: [{
            property: 'threadid',
            direction: 'ASC'
          }]
      });

      var grid = Ext.create('Ext.grid.Panel', {
        id:'button-grid',
        store: common.usageslistDS,
        header : false,
        columns: [
          {text: '',dataIndex: 'id',width:40,hidden:true},
          {text: '类型',dataIndex: 'name',width:200},
          {text: '创建时间',dataIndex: 'created_at',width:110,renderer: Ext.util.Format.dateRenderer('Y-m-d H:i')}
        ],
        columnLines: true,
        selModel: Ext.create('Ext.selection.CheckboxModel'),
        tbar:['-',
          {
            text:'增加',
            width:50,
            iconCls: 'addItem',
            handler:function(){
              openWindow('win','增加',"admin/usages/new",360,132,common.usageslistDS)
            }
          },'-',{
            text:'编辑',
            width:50,
            iconCls: 'editItem',
            handler:function(){
              var records = grid.getSelectionModel().getSelection();
              if(records.length==0){
                Ext.MessageBox.alert('提示信息', '请先选中一条记录。');
              }else{
                openWindow('win','编辑',"admin/usages/"+records[0].get('id')+"/edit",360,132,common.usageslistDS)
              }
            }
          },'-',{
            text:'删除',
            width:50,
            iconCls: 'deleteItem',
            handler:function(){
              var records = grid.getSelectionModel().getSelection();
              if(records.length==0){
                Ext.MessageBox.alert('提示信息', '请先选中一条记录。');
              }else{
                Ext.MessageBox.confirm('警告','确定要删除该记录吗？',function (button){
                  if(button=='yes'){
                    Ext.Ajax.request({
                      url : 'admin/usages/'+records[0].get('id'),
                      method : 'DELETE',
                      waitMsg: '正在提交...',
                      params: {
                        authenticity_token: '<%= form_authenticity_token.to_s %>'
                      },
                      success : function (response,opts) {
                        Ext.MessageBox.alert('消息', '操作成功！');
                        common.usageslistDS.reload();
                      },
                      failure : function (result, response){
                        Ext.MessageBox.alert('消息', response.result);
                      }
                    });
                  }
                })
              }
            }
          }],
        bbar: new Ext.PagingToolbar({
          pageSize: common.list_num,
          store: common.usageslistDS,
          displayInfo: true,
          displayMsg: "显示第 {0} 条到 {1} 条记录，一共 {2} 条",
          emptyMsg: "没有记录"
        }),
        border:false,
        height : Ext.get("<%=params[:controller]%>_<%=params[:action]%>_div").getHeight(),
        iconCls: 'icon-grid'
      });

      grid.render('<%=params[:controller]%>_<%=params[:action]%>_div');
      common.usageslistDS.load();
    })
  </script>
<%end%>

app/views/admin/usages/new.html.erb
<% content_for :header do%>
  <script type="text/javascript">

    Ext.onReady(function(){
      var winForm = new Ext.form.FormPanel({
        url:'admin/usages',
        height: 177,
        width: 364,
        layout: 'absolute',
        border: false,
        frame:true,
        items: [
          {
            xtype: 'label',
            x: 50,
            y: 30,
            height: 20,
            width: 60,
            text: '类型：'
          },
          {
            xtype: 'textfield',
            x: 110,
            y: 30,
            name: 'name',
            width: 210
          },
          {
            xtype: 'button',
            x: 130,
            y: 80,
            height: 30,
            width: 90,
            text: '保存',
            handler: function(){
              if (winForm.form.isValid()) {
                winForm.form.submit({
                  method: 'post',
                  waitMsg: '正在处理...',
                  success: function(result, response){
                    Ext.MessageBox.alert('提示', '成功！');
                    Ext.getCmp('win').close();
                  },
                  failure: function(result, response){
                    Ext.MessageBox.alert('错误提示', response.result.info);
                  }
                });
              }else {
                Ext.MessageBox.alert('错误提示', '请按要求填写必输选项.');
              }
            }
          }
        ]
      });
      winForm.render('<%=params[:controller]%>_<%=params[:action]%>_div');
    });
  </script>
<%end%>